name: nf-benchmark CI
# This workflow is triggered on pushes and PRs to the repository.
# It runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on: [push, pull_request]

jobs:
  test_tcoffee_demo:
    env:
      NXF_VER: ${{ matrix.nxf_ver }}
      NXF_ANSI_LOG: false
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      matrix:
        # Nextflow versions: check pipeline minimum and current latest
        nxf_ver: ['20.10.0']
        paramPipeline: ['--pipeline tcoffee --skip_benchmark']
    steps:
      # Check out the repository
      - uses: actions/checkout@v2
      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Run pipeline as a demo with tcoffee as the pipeline and balibase as the benchmarker
        run: |
          nextflow run ${GITHUB_WORKSPACE} ${{matrix.paramPipeline}} -profile nfb-test,nfb-docker

  test_regressive_alignment:
    env:
      NXF_VER: ${{ matrix.nxf_ver }}
      NXF_ANSI_LOG: false
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      matrix:
        # Nextflow versions: check pipeline minimum and current latest
        nxf_ver: ['20.10.0']
        paramPipeline: ['--pipeline regressive_alignment --pipeline_test_config ./modules/pipelines/regressive_alignment/conf/test_nfb.config --skip_benchmark --align_methods CLUSTALO  --regressive_align false --evaluate false']
    steps:
      # Check out the repository
      - uses: actions/checkout@v2
      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Runs regressive_alignment pipeline on test mode
        run: |
          nextflow run ${GITHUB_WORKSPACE} ${{matrix.paramPipeline}} -profile nfb-test,nfb-docker